### ISSUE TITLE
Any recent updates?

### ISSUE THREAD

**Issue by sadmanca** [expitau-dev/WaterlooWorksNow#2]
Hiya, fellow co-op job posting archiver here*, was wondering if you would be open (or able) to archive the latest cycle(s) of job postings on WaterlooWorks?

Not sure if you've graduated already, but you could also reach out for a Waterloo student in a younger year to "carry the torch" after you, I'm sure there are likeminded archivers like ourselves :)

*https://sadman.ca/posts/analyzing-pey-postings-part-1/

**Comment by expitau** [comment]
Hey Sadman,

Thanks for reaching out, unfortunately as you are not a student of the University of Waterloo, I am unable to share the data that I have scraped with you. You are free to use and modify the code as you wish, or use the old sample data provided in the repository. 

Cheers!
